---
- name: Run docker container
  hosts: docker-base-1
  become: true
  tasks:

    - name: Run container
      docker_container:
        name: reddit
        image: m0rgulnet/otus-reddit:1.0
        detach: yes
        network_mode: host
        ports:
          - "9292:9292"
        state: started
