version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
         aliases:
          - comment_db
          - post_db
  ui:
    build: ./ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
   driver: bridge
   ipam:
      driver: default
      config:
      - subnet: ${FRONT_NETWORK_ADDR}
  back_net:
   driver: bridge
   ipam:
      driver: default
      config:
      - subnet: ${BACK_NETWORK_ADDR}
