version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
         aliases:
          - comment_db
          - post_db

  ui:

    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED} 

  post:

    image: ${USER_NAME}/post:${UI_VERSION}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED} 

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED} 
    
volumes:
  post_db:

    
networks:
  front_net:
   driver: bridge
   ipam:
      driver: default
      config:
      - subnet: ${FRONT_NETWORK_ADDR}
  back_net:
   driver: bridge
   ipam:
      driver: default
      config:
      - subnet: ${BACK_NETWORK_ADDR}
